---
name: N'Gouro dit Issa SANOGO
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: MSc
profilepic: profile.JPG
position: Product Owner Database
address: "[Île-de-France, France](https://maps.app.goo.gl/rMKeW5kvxcZnwoj89)"
phone: +33 6 51 98 52 79
email: ngsanogo@proton.me
www: ngsanogo.rbind.io
linkedin: ngsanogo
github: ngsanogo
aboutme: "Fort d'une expertise approfondie en ingénierie des données, en gestion ainsi que l'analyse de données, je suis prêt à mettre mes compétences au service de votre entreprise. Je suis profondément convaincu que mes solides compétences techniques et de gestion de projet, mon expérience professionnelle diversifiée et mes qualités personnelles me permettront d'apporter une valeur ajoutée significative à votre entreprise."
headcolor: 414141
output: vitae::awesomecv
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(vitae)
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  results = "asis"
)
options(stringsAsFactors = FALSE)
lan <- "fr"
```

`r ifelse(lan == "en", print("# Professional experiences"), print("# Expériences professionnelles"))`

```{r exp pro}
read.csv(file = "./data/professional_experience.csv", fileEncoding = "UTF-8") |>
  vitae::filter(langue == lan & role != "Data manager (stage de fin d’études)") |> 
  detailed_entries(
    with = company,
    where = loc,
    what = role,
    when = date,
    why = details
  )
```

`r ifelse(lan == "en", print("# Educations"), print("# Formations"))`

```{r formation}
read.csv(file = "./data/education_background.csv", fileEncoding = "UTF-8") |>
  vitae::filter(langue == lan) |>
  slice(1:2) |> 
  detailed_entries(
    with = uni,
    where = loc,
    what = degree,
    when = date,
    why = details
  )
```

`r ifelse(lan == "en", print("# Technical stack and Languages"), print("# Stack technique et Langues"))`

```{r comp}
read.csv(file = "./data/skills.csv", fileEncoding = "UTF-8") |>
  vitae::filter(langue == lan) |>
  slice(-c(1:2)) |> 
  detailed_entries(what = type, why = details)
```
