---
name: N'Gouro dit Issa SANOGO
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: MSc
profilepic: profile.jpeg
position: Data scientist
address: "[Bezons, Île-de-France](https://goo.gl/maps/vPFx9nZWzKZzKzhY8)"
phone: +33 6 51 98 52 79
email: ngsanogo@gmail.com
www: ngsanogo.rbind.io
linkedin: ngsanogo
github: ngsanogo
headcolor: 414141
output: vitae::awesomecv
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(vitae)
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  results = "asis"
)
options(stringsAsFactors = FALSE)
lan <- "fr"
```

`r ifelse(lan == "en", print("# Professional experiences"), print("# Expériences professionnelles"))`

```{r exp pro}
read.csv(file = "./data/professional_experience.csv", fileEncoding = "UTF-8") %>%
  filter(langue == lan & role != "Data manager (stage de fin d’études)") %>% 
  detailed_entries(
    with = company,
    where = loc,
    what = role,
    when = date,
    why = details
  )
```


```{r exp consult, eval=FALSE}
#`r ifelse(lan == "en", print("# Consulting experience"), print("# Expérience de consultant"))`
read.csv(file = "./data/consulting_experience.csv", fileEncoding = "UTF-8") %>%
  filter(langue == lan) %>% 
  detailed_entries(
    with = company,
    where = loc,
    what = role,
    when = date,
    why = details
  )
```


```{r open proj, eval=FALSE}
#`r ifelse(lan == "en", print("# Open source projects"), print("# Projets open source"))`
read.csv(file = "./data/opensource_project.csv", fileEncoding = "UTF-8") %>%
  filter(langue == lan) %>% 
  detailed_entries(
    with = company,
    where = loc,
    what = role,
    when = date,
    why = details
  )
```

`r ifelse(lan == "en", print("# Educations"), print("# Formations"))`

```{r formation}
read.csv(file = "./data/education_background.csv", fileEncoding = "UTF-8") %>%
  filter(langue == lan & grepl(degree, pattern = "^master", ignore.case = TRUE)) %>% 
  detailed_entries(
    with = uni,
    where = loc,
    what = degree,
    when = date,
    why = details
  )
```

`r ifelse(lan == "en", print("# Skills and Languages"), print("# Compétences, Informatiques et Langues"))`

```{r comp}
read.csv(file = "./data/skills.csv", fileEncoding = "UTF-8") %>%
  filter(langue == lan) %>% 
  detailed_entries(what = type, why = details)
```
